name: OpifyItems
version: 1.0.2
main: vb.$opifyitems.PluginMain
author: UltraPlays
softdepend: [EssentialsX]
api-version: 1.13
commands:
  opify:
    description: Max out any item /opitem (enchant)
    permission: ultraplugins.opitems
    permission-message: You are not powerful enough!
